input type:keyboard {
  xkb_numlock enabled
  xkb_layout "us,ru"
  xkb_variant ",phonetic"
  xkb_options "grp:win_space_toggle"
}

input "type:touchpad" {
  tap enabled
  natural_scroll disabled
  pointer_accel -0.1
  accel_profile flat
}

input "type:pointer" {
  pointer_accel -0.3
  accel_profile flat
}
